- .github/workflows/terraform.yml
> testing jira deployment

- .github/workflows/terraform.yml
> fix enviroment name

- cmd/codebuild/reset/main.go
changes in calling the function that notifies error in nuke account
> fix: modify calling the function & adding more logs

- cmd/codebuild/reset/main.go
> Add Logs To QA

- cmd/codebuild/reset/main.go
…e directly
move log.Fatalf to the end of the code since it will stop the code and exit
>  Skip Existing Code when Nuke Account Failed

- cmd/codebuild/reset/main.go
- modules/reset_codebuild.tf
adding sns topic and send message whenever an account reset fails
> feat: add sns topic & send message when accoutn reset fails

- cmd/lambda/lease_auth/create.go
- modules/accounts_lambda.tf
update session time 
try to use email for session name (testing)
> update session time use email for session name to QA

- cmd/lambda/lease_auth/create.go
append email to role session name and adjust principal session time
> append email to roleSessionName To QA

- cmd/lambda/lease_auth/create.go
remove double quotes , since body is being passed as a string
> remove double quotes from request body

- cmd/lambda/lease_auth/create.go
> increase signinToken duration to QA

- cmd/lambda/lease_auth/create.go
remove session duration ( we need to manually update role on each account before changing the code
> remove session duration To QA

- cmd/lambda/lease_auth/create.go
- pkg/accountmanager/service.go
> remove MaxsessionDuration modification

- modules/fixtures/policies/bluepi_policies/bluepi_policy_basic.tmpl
adding a new folder to store custom bluepi policies
> add new bluepi policies folder

- modules/artifacts_bucket.tf
add terraform code to upload files
> fix : add terraform to upload the files

- modules/artifacts_bucket.tf
> comment code

- modules/artifacts_bucket.tf
> comment variables

- modules/artifacts_bucket.tf
> remove all added variables

- modules/artifacts_bucket.tf
> feat : upload policy file test

- modules/accounts_lambda.tf
- modules/artifacts_bucket.tf
- modules/fixtures/policies/bluepi_policy_basic.tmpl
- modules/update_principal_policy_lambda.tf
- modules/variables.tf
- pkg/accountmanager/iam.go
- pkg/accountmanager/service.go
> add bluepi methods to create a custom role

- modules/accounts_lambda.tf
- modules/artifacts_bucket.tf
> fixing format with terraform

- pkg/accountmanager/iam.go
> fix : add more logs

- pkg/accountmanager/iam.go
> fix: add logging in build policy

- cmd/codebuild/reset/default-nuke-config-template.yml
- pkg/accountmanager/iam.go
> update build policy function and buke configuration template

- cmd/codebuild/reset/default-nuke-config-template.yml
- modules/fixtures/policies/bluepi_policy_basic.tmpl
- pkg/accountmanager/iam.go
- pkg/accountmanager/service.go
> update aws nuke account config and fix attach role to policy 

- pkg/accountmanager/service.go
> add log for policy creation

- cmd/codebuild/reset/default-nuke-config-template.yml
- pkg/accountmanager/iam.go
> add custom roles and policies

- cmd/codebuild/reset/default-nuke-config-template.yml
> specify exact policy name 

- cmd/codebuild/reset/default-nuke-config-template.yml
> change condition from exact to contains

- cmd/codebuild/reset/default-nuke-config-template.yml
> try regex instead of contains

- cmd/lambda/lease_auth/create.go
- modules/artifacts_bucket.tf
> formating with terraform

- modules/artifacts_bucket.tf
> fix: artifact bucket resources

- cmd/lambda/lease_auth/create.go
> authenticate lease using custom roles 

- cmd/lambda/lease_auth/create.go
> add durationSeconds for signin token

- modules/fixtures/policies/bluepi_policy_basic.tmpl
- pkg/accountmanager/iam.go
> fix : try to update policy

- pkg/accountmanager/service.go
> fix: try to update roles when lease is created

- pkg/accountmanager/service.go
> fix: remove policies

- pkg/accountmanager/service.go
> fix delete roles

- pkg/accountmanager/service.go
> fix create policy

- modules/fixtures/policies/bluepi_policy_basic.tmpl
> fix : update policy files

- pkg/accountmanager/service.go
> fix: mergerole wrong params

- modules/fixtures/policies/bluepi_policy_basic.tmpl
> fix : modify policy

- cmd/lambda/lease_auth/create.go
> fix: add logs to check request body

- modules/variables.tf
- pkg/accountmanager/iam.go
- pkg/accountmanager/service.go
> add description to policy

- cmd/codebuild/reset/main.go
> reset fail sns topic fix to dev

- modules/reset.tf
> add policy to account reset queue

- modules/reset.tf
> fix format

- cmd/lambda/lease_auth/create.go
> add sessionDuration test

- cmd/lambda/lease_auth/create.go
> Revert "add sessionDuration test"

- modules/reset.tf
> feat: add policy to send message to queue

- modules/reset.tf
> fix: remove comment

- cmd/lambda/lease_auth/create.go
> fix: trim exceeding character above 64

- modules/fixtures/policies/bluepi_policy_basic.tmpl
- modules/fixtures/policies/bluepi_policy_serverless.tmpl
- modules/fixtures/policies/principal_policy.tmpl
- add  ssm-guiconnect to policy
> add ssm-guiconnect policy to roles
